# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d154482b90aeb7c6b074613ae58c9fa72f5e519520a3d8231be22ae0ed3d2c3d5391f8c18809e8f5dd6e7fd7ff071ac5e75a78f47049f659adf3b6f9d49928b

test:
  secret_key_base: f188fb63d0ff550b1e38ad0e930c6fa635a48cecfd6d870f5807f8d9d87b1038d6473eccf7ddd8a76c7976a7cd2c66b0957b4a4fc6a7acd63062bed803d97a6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
